### ISSUE TITLE
Maintain a develop branch

### ISSUE THREAD

**Issue by kmehant** [cloudlibz/gocloud#10]
One of the best practice is to maintain two branches.

1. Develop - for all the developer commits to the project
2. master -  to sync the code which doesn't break the build and use it for building the main project.

**Comment by rehrumesh** [comment]
Hi @kmehant, agree and we are aware of these practices. We are in the process of redesigning the entire process. We will incorporate these aspects as well. Hense closing the issue.

**Comment by kmehant** [comment]
@rehrumesh thank you, I opened this issue as part of GCI task :)
