### ISSUE TITLE
Suggestion: Add more information about what gocloud does/how to install

### ISSUE THREAD

**Issue by virenkhandal** [cloudlibz/gocloud#12]
In the current README.md file, there is the logo, the providers, and a basic thesis about what gocloud is all about. After reading this, many users may not understand how the repo works and/or what it does.

A small description should be added to thoroughly explain how gocloud actually works.

The description can go something like this: "gocloud can be installed by inputting this code into Terminal or any other code editing software. <insert code>. gocloud is mostly operated online, so it can be found at <insert link>."

Adding this description can increase collaboration and increase productivity on this repo. The first step to any problem is understanding, as the Transcendentalists once confirmed. A description will enhance understanding and give users the first step to solving an issue or working on a project.

**Comment by rehrumesh** [comment]
Hi @virenkhandal can you please elaborate more? I don't think I understood it well.

**Comment by rehrumesh** [comment]
An example would be ideal

**Comment by rajikaimal** [comment]
You can find all the information in this page. @virenkhandal 

https://github.com/scorelab/GSoC/blob/master/GSoC-2017/Pratik_Dhanave_GoCloud.md

**Comment by AdhyanDhull** [comment]
@rajikaimal I would like to mention that there is no information regarding how to setup/install and run GoCloud on a local machine. Even the repository of Pratik Dhanave doesn't have that info in the wiki.

**Comment by PratikDhanave** [comment]
@virenkhandal we have this information in docs of gocloud.
