### ISSUE TITLE
Suggestion: Expanding to New Cloud Networks

### ISSUE THREAD

**Issue by virenkhandal** [cloudlibz/gocloud#13]
Currently, gocloud provides servicing with Amazon AWS and Google Cloud softwares, which restricts the use of many different cloud providing softwares. As technology grows and expands, there are more resources that people use to save files and access the cloud.

Some of the fastest growing cloud providers are Verizon Cloud, DropBox, and IBM Cloud. As the two services: Google Cloud and Amazon AWS have been provided for gocloud, the new cloud services can be provided similarly, as well.

Overall, expanding to new, fast-growing cloud providers can significantly increase collaboration on gocloud's projects and codes.

**Comment by rehrumesh** [comment]
Already in the roadmap. Hence closing
