### ISSUE TITLE
Top  Cloud Providers

### ISSUE THREAD

**Issue by iammosespaulr** [cloudlibz/gocloud#19]
# Microsoft Azure

       It's a little more difficult to figure out how much revenue Microsoft generates from cloud computing. In its fiscal 2016 Q4 report, the company said that its "Intelligent Cloud" revenue increased 5 percent to reach $6.7 billion. That makes it seem like Microsoft does more cloud business than Amazon, except that Microsoft includes its very substantial server revenues along with its Azure cloud computing service in the Intelligent Cloud category. The company has previously said that its Azure business is on a $10 billion annual run rate, or around $2.5 billion in revenue per quarter. Most market analysts put it in the number two spot behind Amazon.

       In addition to its Azure IaaS and PaaS offerings, Microsoft also has several SaaS offerings, including its Office 365 products, the online versions of its Dynamics line of enterprise software and its online developer tools.

   Get an in-depth look at [Azure](http://www.datamation.com/cloud-computing/microsoft-azure.html).
# IBM Cloud
       Although it hasn't always been considered one of the "big three" cloud computing vendors, IBM's cloud business has been coming on strong. In its most recent quarterly report, IBM said that its "cloud-as-a-service revenue was up 50 percent," and had an annual run rate of $6.7 billion.

      IBM's most visible cloud service is its Bluemix PaaS, which is aimed primarily at enterprise development teams. The company also a lot of enterprise software on a SaaS basis, and it sells cloud infrastructure, cloud management tools and cloud managed services.

       Get an in-depth look at [IBM Cloud](http://www.datamation.com/cloud-computing/ibm-cloud.html).

# Adobe
    Adobe offers many products that provide cloud services. Few among them are Adobe Creative Cloud, Adobe Experience Cloud and Adobe Document Cloud etc.
    Adobe Creative Cloud service is a SaaS, that offers its users to access the tools offered by Adobe like editing the videos, photography, graphic designing etc.
    Adobe Experience Cloud offers its users to access a broad set of solutions for advertising, building campaigns and gaining intelligence on business.
    Adobe Document Cloud is a complete solution for digital documentation.

For more information on this service, visit [Adobe website](http://www.adobe.com/in/).
 # Vmware 
    VMware is a universal leader in virtualization and Cloud Infrastructure.
    VMware’s cloud computing is exclusive and helps in reducing the IT intricacy, lower the expenses, provides flexible agile services etc.
    VMware vCloud Air is a safe and protected public cloud platform that offers networking, storage, disaster recovery and computing etc.
    VMware’s Cloud solutions facilitate to maximize your organization’s profits of cloud computing by combining the services, technologies, guidance needed to operate and manage the staff etc.

Visit this website for further details on [VMware Cloud service](http://www.vmware.com/in/cloud-services/infrastructure.html). 
# Redhat
    Red Hat is an Open Cloud technology used by IT organizations to deliver agile and flexible solutions.
    Using Red Hat Cloud we can modernize the apps, update and manage them from a single place and integrate all the desired parts into a single solution.
    Red Hat Cloud Infrastructure helps us to build and manage an open cum private cloud at low cost.
    Red Hat Open Shift is an open and hybrid service used by developers to develop, deploy, host and delivers the applications quickly.

You can visit the [Red Hat website](https://www.redhat.com/en/technologies/cloud-computing) and browse for more information regarding cloud computing.

**Comment by iammosespaulr** [comment]
@rajikaimal Could you review this task for me https://codein.withgoogle.com/dashboard/task-instances/5501678990131200/

**Comment by rajikaimal** [comment]
Reviewed 😃

**Comment by iammosespaulr** [comment]
@rajikaimal Thank you so much...

**Comment by iammosespaulr** [comment]
@rajikaimal are you available on gitter
