### ISSUE TITLE
List of rising/trending cloud providers

### ISSUE THREAD

**Issue by Kalyan3578** [cloudlibz/gocloud#24]
List of rising/trending cloud providers with their advantages aside from GCP and AWS.

**1. [Atlantic.net](https://www.atlantic.net)**
Atlantic.Net is a trusted and proven hosting company in web hosting industry. It's reputation is founded upon over twenty years of direction and counsel given to CEOs, managers, engineers, and IT professionals. Clients and affiliates know they can rely on its support and services to make their businesses grow and prosper. Customer satisfaction is, always has been, and forever will be paramount at Atlantic.Net. You can depend on it!

- API controls 
- Storage API
- SSL Certificates 

![atlantic net](https://user-images.githubusercontent.com/34546340/34722478-194a7b5c-f56d-11e7-8453-0e7ce2ea8d44.png)

**2. [Microsoft Azure](https://azure.microsoft.com/en-us/)**
Azure Virtual Machines lets users deploy a wide range of computing solutions. Users can deploy a virtual machine nearly instantly, and pay by the minute. With support for Microsoft Windows, Linux, Microsoft SQL Server, Oracle, IBM, SAP, and Azure BizTalk Services, users can deploy any workload and any language on nearly any operating system. Azure Storage provides users with the ability to scale, to store, and retrieve large amounts of data. Azure Blob Storage is used to store unstructured data, such as documents and media files. Azure Table Storage is functional for structured NoSQL data. Users can use Azure Queue Storage to reliably store messages, and the SMB-based Azure File Storage for existing or new applications.

- Virtual Networking API
- Compute API
- Storage Provider API
- Analytics of final reults

![microsoft azure](https://user-images.githubusercontent.com/34546340/34722787-34c2edd2-f56e-11e7-9671-649bba96d2eb.png)

**3. [IBM Cloud](https://www.ibm.com/cloud/)**
The IBM Cloud has been built to help you solve problems and advance opportunities in a world flush with data. Whether it’s data you possess, data outside your firewall, or data that’s coming, the IBM Cloud helps you protect it, move it, integrate it and unlock intelligence from it — giving you what it takes to prevail in a competitive market.

- SoftLayer Computing API
- Infrastructure 
- Object Storage API

![ibm cloud](https://user-images.githubusercontent.com/34546340/34723061-382db604-f56f-11e7-870a-6351b19ab7b9.png)

**4. [Rackspace](https://www.rackspace.com)**
Users can instantly provision bare-metal servers using the OpenStack API or the control panel to bring more consistency and predictability to application performance. It offers hosts for virtual machine flavor classes, as well as all the bare-metal servers, receive redundant, dual, bonded 10Gbps network connections to fuel high-bandwidth applications. All servers also have a blazing 10Gbps connection to Cloud Block Storage. OnMetal servers are single-tenant, bare metal servers provisioned via the same OpenStack API as the Rackspace cloud. They can be spun up or down as quickly as VMs to offer the agility of multi-tenant environments with the performance of single-tenant hardware. OnMetal servers are engineered as 100 percent solid-state with external cooling. This provides increased mean time between failures (MTBF).

- Monitoring 
- OpenStack API
- Control Panel
- Block Storage API
- Infrastructure services

![rackspace](https://user-images.githubusercontent.com/34546340/34723450-ad6628c4-f570-11e7-8e0a-5e78f5537ed5.png)

**5. [GoDaddy](https://in.godaddy.com/hosting/dedicated-server)**
GoDaddy was using a hosting company from India and it had a great deal of trouble with their tech support. Their English was mediocre and their response time to issue was very slow. It could take several days before we heard from them, and weeks to solve the issue. The cost was very high, thousands of dollars per month. Their servers experienced a security breach and we lost 3 of our websites permanently because their backup system failed. GoDaddy offers immediate and expert tech support. They provide daily backup and restore services. The cost is less than $100 per month for the same amount of cloud space we had with our former company. They use the cloud servers for web hosting, as well as email hosting. They also use their domain name service. GoDaddy has performed above and beyond the call of duty. It has benefited us by have minimal downtime for its websites, fast loading speeds and extreme diligence in solving issues. It have very few issues.

- Backups
- Solid-State Drive API
- DNS API

![godaddy](https://user-images.githubusercontent.com/34546340/34723843-ef241842-f571-11e7-8383-cdbd18a82302.png)

[Information and image source](https://clutch.co/cloud)

**Comment by rehrumesh** [comment]
You should list down the developer API's they are providing as well as what are the core components which are in align with gocloud. For example Azure provides a virtual computing component which can be implemented in parallel with AWS EC2 instances and Google Compute instances. All three will share the same interface.

**Comment by Kalyan3578** [comment]
Comment has been updated!

Thanks for correcting me! :-)
