### ISSUE TITLE
Error in test cases & Naming suggestion for AWS LoadConfig()

### ISSUE THREAD

**Issue by OddCN** [cloudlibz/gocloud#49]
# Issue Overview

In auth package, the auth.LoadConfig() function already renamed as auth.AWSLoadConfig().
But int test cases such as [compute/ec2/instance_test.go](https://github.com/cloudlibz/gocloud/blob/master/compute/ec2/instance_test.go), [container/awscontainer/container_test.go](https://github.com/cloudlibz/gocloud/blob/master/container/awscontainer/container_test.go), etc.Inside the init() function of the test cases is still the previous method - auth.LoadConfig().

# Suggestion

Rename auth.AWSLoadConfig() as awsAuth.LoadConfig(), and fix usages 's name of this package function. This will be more applicable to other auth of cloud naming, such as aliAuth.LoadConfig(), azureAuth.LoadConfig().

**Comment by shlokgilda** [comment]
The suggestions do make sense. If everyone agrees to the naming conventions, I believe that we can go ahead with this.

**Comment by PratikDhanave** [comment]
+1

**Comment by shlokgilda** [comment]
Should we start using the naming convention suggested for further development?
