### ISSUE TITLE
Google Code-In 2017: Getting Started Issue

### ISSUE THREAD

**Issue by lakindu95** [cloudlibz/gocloud#8]
THIS IS A NOT A REAL ISSUE BUT A PLACEHOLDER.

All the practising PRs for Google Code-In 2017 should refer this issue. PRs referring this issue will be closed without merging. Do not refer this issue if you are NOT submitting a practice PR and need your work merged.

**Comment by dhs17y1fwarrenjinchenghao** [comment]
https://github.com/dhs17y1fwarrenjinchenghao/gocloud
does this count as a link to the forked repo?

**Comment by rajikaimal** [comment]
Hi @dhs17y1fwarrenjinchenghao, yes it's a forked repository nice work.

**Comment by shravyanandyala** [comment]
https://github.com/cloudlibz/gocloud/issues/9
