### ISSUE TITLE
Fix to gocloud/compute/ec2/region.go

### ISSUE THREAD

**Issue by shravyanandyala** [cloudlibz/gocloud#9]
In this, only one region (USEast) is defined although there are many more in AWS. More diverse regions' information (sa-east-1, eu-west-2, etc.) should be included as other variables so that it is convenient for people to use these prepared constants rather than instantiating a region with the information each time they would like to reference it.

**Comment by pranjaltale16** [comment]
@rehrumesh @PratikDhanave 
Hello,
I would like to work on this issue.
I think we can add all the elements of [this](https://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region) list [here](https://github.com/cloudlibz/gocloud/blob/master/compute/ec2/region.go).

**Comment by PratikDhanave** [comment]
hi pranjal we are passing this as  parameter
